### ISSUE TITLE
https://rspec.info has an invalid SSL cert

### ISSUE THREAD

**Issue by llimllib** [rspec/rspec.github.io#102]
![rspec behaviour driven development for ruby 2017-01-20 15-52-41](https://cloud.githubusercontent.com/assets/7150/22165177/80b01ed4-df28-11e6-86b1-c35e6d856c44.png)

Looks like an invalid common name on your cert?

**Comment by JonRowe** [comment]
Thats because we don't have a SSL certificate. The RSpec website is a Github page and Github pages don't support SSL for custom domains.

**Comment by JonRowe** [comment]
You can access it as https://rspec.github.io if you would like transport security :joy:
