### ISSUE TITLE
Docs javascript not referenced correctly for 3.6 docs

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#108]
On the docs pages for each library, there is a search box for classes, methods and files that uses JS for a nice experience.  Here's a working example:

http://rspec.info/documentation/3.5/rspec-core/

But if you try that same page on 3.6 the JS isn't working:

http://rspec.info/documentation/3.6/rspec-core/

If you look at the `<head>` for each page, you can see they reference the javascript files differently:

```
<script type="text/javascript" charset="utf-8" src="js/jquery.js"></script>

<script type="text/javascript" charset="utf-8" src="js/app.js"></script>
```

(That's 3.6 where it's not working.)

vs

```
<script type="text/javascript" charset="utf-8" src="/javascripts/docs/jquery.js"></script>

<script type="text/javascript" charset="utf-8" src="/javascripts/docs/app.js"></script>
```

(That's 3.5 where it is working.)

@JonRowe do you have any ideas what's causing this?

@samphippen did you get any strange warnings when you generated the docs for 3.6?

**Comment by samphippen** [comment]
I didn't see anything unusual, this may just be a bug in the generator. @JonRowe any ideas?

**Comment by JonRowe** [comment]
Did you use the rake task in `rspec-dev`? Did you have `ag` installed?

**Comment by samphippen** [comment]
ah, I do not have ag installed.

**Comment by JonRowe** [comment]
Should be all fixed now
> 
> 
>

**Comment by myronmarston** [comment]
Thanks for fixing it, @JonRowe!  Can you add something to our tools that will abort with a clear error if `ag` is not installed so this doesn't happen again?

**Comment by pirj** [comment]
Works fine from 3.5 to 3.9.
[`ag` check](https://github.com/rspec/rspec-dev/blob/master/Rakefile#L64) is in place.
I suppose we're done with this problem.
