### ISSUE TITLE
3.8 docs are slightly messed up

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#116]
See [rspec-core on staging](http://rspec-staging.github.io/documentation/3/rspec-core/) for example:

![image](https://user-images.githubusercontent.com/49391/43680287-fb4602ee-97eb-11e8-8cc3-e7ea70e716ef.png)

The 3.8 docs for mocks and expectations are slightly messed up, too, but the rails docs are kinda messed up.

@JonRowe any ideas?

**Comment by myronmarston** [comment]
@JonRowe can you take a look at this?

**Comment by JonRowe** [comment]
On my list!

**Comment by benoittgt** [comment]
Ping me if I can help.

**Comment by JonRowe** [comment]
Right so this is due to an updated version of yard changing the js, I think we should use the versions it generates rather than shared, staging has been updated with fixed docs and see #117 and rspec/rspec-dev#206

**Comment by JonRowe** [comment]
If someone can sanity check I'll ship to prod

**Comment by myronmarston** [comment]
Staging LGTM

**Comment by JonRowe** [comment]
Deployed to prod

**Comment by pirj** [comment]
Please re-open if you feel something needs to be done in the scope of this issue.
