### ISSUE TITLE
patreon for RSpec

### ISSUE THREAD

**Issue by equivalent** [rspec/rspec.github.io#127]
is RSpec core team considering opening Patreon account ?  

I'm one of many developers that don't have time to contribute with code but feel guilty and would happily contributed  with some monthly micro-payment for all the effort you guys are doing.

**Comment by JonRowe** [comment]
We have an open-collective account for general donations, and I (the current maintainer) am on the Github sponsors program, just haven't gotten around to any kind of page on the website or setting up the repo buttons :joy:

**Comment by benoittgt** [comment]
With the amount of time Jon spend on RSpec. @equivalent I think you can sponsor him. :)

Thanks a lot! <3

**Comment by JonRowe** [comment]
Thanks a lot @equivalent :)

**Comment by equivalent** [comment]
No, thank you guys for RSpec. It creates huge impact on my development life. For 10years now makes me happy to write tests.
