### ISSUE TITLE
http://rspec.info/ja/blog/ styling is broken

### ISSUE THREAD

**Issue by pirj** [rspec/rspec.github.io#147]
![image](https://user-images.githubusercontent.com/6916/82714069-d53fa680-9c95-11ea-8786-8dcb1546c772.png)
vs
![image](https://user-images.githubusercontent.com/6916/82714086-dec90e80-9c95-11ea-8984-6942a35cb6c9.png)

**Comment by JonRowe** [comment]
Probably a css path issue?

**Comment by pirj** [comment]
js.css is missing

**Comment by pirj** [comment]
Additionally, the Japanese blog only has those articles:
2015-11-13-rspec-3-4-has-been-released.md
2016-07-01-rspec-3-5-has-been-released.md
2017-05-04-rspec-3-6-has-been-released.md
2017-10-17-rspec-3-7-has-been-released.md
but /ja/blog/ lists all of them and links refer to English articles.

There seems to be something inherently broken, and #146 seems a better way to address those issues.
