### ISSUE TITLE
Layout is broken for "Inherits" in < 3.9

### ISSUE THREAD

**Issue by pirj** [rspec/rspec.github.io#148]
http://rspec.info/documentation/3.8/rspec-core/RSpec/Core/Example/Procsy.html
![image](https://user-images.githubusercontent.com/6916/82714175-323b5c80-9c96-11ea-8583-f72a509a5db3.png)
http://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Example/Procsy.html
![image](https://user-images.githubusercontent.com/6916/82714195-4a12e080-9c96-11ea-8e7b-fb1faa67d787.png)
![image](https://user-images.githubusercontent.com/6916/82714203-5139ee80-9c96-11ea-8a64-654fc08221de.png)

The same on the other doc pages:
![image](https://user-images.githubusercontent.com/6916/82714220-5eef7400-9c96-11ea-8b44-ce3c081c553f.png)

Same on 3.7 and 3.8, didn't look further.

**Comment by benoittgt** [comment]
This probably related to the yard version. 

* 3.8: Generated on Fri Sep 14 00:01:55 2018 by yard 0.9.16 (ruby-2.5.1).
* 3.9: Generated on Wed Apr 8 18:11:34 2020 by yard 0.9.24 (ruby-2.6.3).

This is done here https://github.com/lsegal/yard/blob/master/templates/default/module/html/box_info.erb#L7-L10

I can look at it.

**Comment by JonRowe** [comment]
Thanks @benoittgt !

**Comment by benoittgt** [comment]
Hello @pirj 

I am sorry but what is broken? Expect this is now hidden by default what we should see?

Thanks :)

**Comment by pirj** [comment]
Hey @benoittgt ! 👋 :D

There's no `(hide)` button as far as I can tell.
Also, there's a white rectangle somewhere near `Inherits`.

I didn't dig the source, but it seems there's a difference:

![image](https://user-images.githubusercontent.com/6916/84051718-3797e700-a9b8-11ea-85a4-67c99e1986b0.png)

![image](https://user-images.githubusercontent.com/6916/84051821-55fde280-a9b8-11ea-89ba-843d2b9af816.png)

**Comment by benoittgt** [comment]
Oook. Thanks @pirj
