### ISSUE TITLE
Many relative links are broken (because Github Pages adds trailing slashes)

### ISSUE THREAD

**Issue by danieldiekmeier** [rspec/rspec.github.io#188]
Hello! I recently submitted the PR #187 that fixed a few relative links on the website.

After, I wondered if there were any more. I checked out the repo, started middleman and ran [broken-link-checker](https://www.npmjs.com/package/broken-link-checker). I was surprised to find: It reported the exact links that I just fixed.

Indeed: Due to the fact that middleman does NOT add trailing slashes to paths, but Github Pages does, the website works perfectly fine in development, but not in production.

I installed Rack Rewrite and added this to the `config.rb` to sync the behaviour:

```rb
require 'rack/rewrite'

configure :development do
  use ::Rack::Rewrite do
    # add trailing slash, like Github Pages
    r301 %r{/features/(.*)}, '/features/$1/', not: %r{/$}
  end
end
```

I ran the broken-link-checker again, and this time, it found links that were really broken, around ~75. I think they all have the same problem, that don't account for the trailing slash.

I was wondering if it would make sense to fix these in a PR or not? I noticed that the markdown files basically mirror the files in the repo: https://github.com/rspec/rspec-rails/blob/main/features/controller_specs/README.md so I'd guess that it doesn't make sense to edit all the files here manually?

I'd be happy to help, but I think I need someone to point me in the right direction.

**Comment by pirj** [comment]
We use the umbrella `rspec-dev` repo to run [a task](https://github.com/rspec/rspec-dev/blob/a2a50c9c855a1666194a139264b99fa735176617/Rakefile#L216) that converts projects' gherkin to Markdown and puts it in this repo.
E.g. [this doc](https://github.com/rspec/rspec.github.io/blob/109e19f2876f46e31232979c053f9e1e13b369cf/source/features/6-0/rspec-rails/controller-specs/controller-spec.html.md?plain=1#L1) that you've fixed is generated from [this feature spec](https://github.com/rspec/rspec-rails/blob/c76c1e650a2cf34a82963bbb5063112c50cb9ab3/features/controller_specs/controller_spec.feature#L1).

If this process results in broken links, next time we run this task will overwrite what you've manually fixed.
Do you think you know how to fix this?
Adding a broken link checker would be a very nice addition to our CI, which we don't really have in this repo.
