### ISSUE TITLE
Blog post headings mis-sized

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#47]
If you look at one of the blog posts that has titled sections, you'll notice that the section headings are styled identically to the blog post title.  This is because they are all `<h2>` tags.

Ideally the section headings would be styled to look less prominent. I think the solution is to change the [blog post template](https://github.com/rspec/rspec.github.io/blob/2dd9342e2e12157ea9c80e77bb0637c2aa038cbf/source/layouts/blog_post.slim#L4) to use an `<h1>` for the blog post title and then update the styles appropriately.

**Comment by JonRowe** [comment]
Deployed those few PRs to staging...
