### ISSUE TITLE
Broken `Rspec.html` link for rspec-rails docs

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#50]
On the rspec-rails docs page:

http://rspec.info/documentation/3.2/rspec-rails/

Click on "Class List" and you'll see that `RSpec` and `Rspec` are both listed. The latter 404s, while the former goes to a page that talks about `Rspec`.

**Comment by JonRowe** [comment]
I think this is an issue with the generated docs, not with pages itself, I seem to recall there should be two pages...

**Comment by myronmarston** [comment]
> I think this is an issue with the generated docs, not with pages itself, I seem to recall there should be two pages...

I think you're right.  It looks like it works when I run `yard server --reload` from within `rspec-rails` but if I run `yard doc` to generate the static HTML docs it has problems.

**Comment by JonRowe** [comment]
Yeah so I think thats because OSX filesystem is case insensitive, where as git is case sensitive.

**Comment by myronmarston** [comment]
That makes sense.  Maybe we should exclude the `Rspec` constant from the docs by labelling it `@private`?  Or does it have important stuff in there that needs to be publicly documented?

**Comment by JonRowe** [comment]
A quite scan of `rspec-rails` says that it's there only for compatibility with Rails autoloading, and all the child classes are labeled `@private` so I think thats the go /cc @cupakromer

**Comment by cupakromer** [comment]
Yes it is just for making Rails happy. We probably could try to declare it with the Rails inflections, but just marking it `@private` is faster and safer for now.

**Comment by chi6rag** [comment]
A temporary solution is replacing Rspec.html with RSpec.html

**Comment by JonRowe** [comment]
@chi6rag would be better to remove the link to Rspec.html as Rspec.html and RSpec.html do have different content

**Comment by pirj** [comment]
`Rspec` stopped appearing in the Class List starting from 3.4 http://rspec.info/documentation/3.4/rspec-rails/
3.2 and 3.3 are still problematic, but it's unlikely something we'd like to fix.
