### ISSUE TITLE
Frames links on rspec-rails docs 404

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#51]
If you go to any rspec-rails doc page, and click on the "frames" link at the top, it 404s.  For example:

http://rspec.info/documentation/3.2/rspec-rails/RSpec/Rails.html

links to

http://rspec.info/documentation/3.2/rspec-rails/frames.html#!http%3A//rspec.info/documentation/3.2/rspec-rails/RSpec/Rails.html

What's weird is this is only a case for rspec-rails.  It's not a problem for the other projects.

**Comment by pirj** [comment]
It's the case for 3.2, but starting from 3.3 this is not an issue.
https://rspec.info/documentation/3.3/rspec-rails/RSpec/Rails.html
