### ISSUE TITLE
Deploy occasionally borks doc styling

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec.github.io#61]
This happened to me before and it appears to have happened again:

![screen shot 2015-02-01 at 4 46 50 pm](https://cloud.githubusercontent.com/assets/49391/5994689/0beab50a-aa32-11e4-878f-291a954c9f5e.png)

I'll be deploying shortly to get @JonRowe's improvements out there, which should hopefully fix the issue but we should figure out why it happens.

**Comment by myronmarston** [comment]
This was fixed by another deploy.  No idea why it breaks occasionally.

**Comment by JonRowe** [comment]
I've had it happen once to me, but only once, so NFI :/

**Comment by aaronmcadam** [comment]
This happens to me almost all the time with YARD whilst running it locally, then I have to refresh the browser and the styles kick in

**Comment by pirj** [comment]
I haven't personally experienced this lately on my memory.
Let's close this for now and re-open if it becomes the issue again.
